### ISSUE TITLE
quitar pagina de redes sociales si no funciona

### ISSUE THREAD

**Issue by jmanuellh** [ProyectoMigala/RepoDinamico#7]
solo tener cosas que funcionen.
de nada le sirve al usuario tener un letrero de proximamente.
opciones:
1. quitar pestaña "redes sociales"
2. quitar de comisiones estatales para abajo:
![fasdgdsgasdgdagf](https://github.com/ProyectoMigala/proyectomigala.github.io/assets/12085233/02ca42b4-f876-4cbd-8539-90c7d568e169)

**Comment by kevin4moe** [comment]
Totalmente de acuerdo, no he tenido tiempo pero mi propuesta es conectar esta pagina con el repo que actualmente existe de directorio, así no mantener dos proyectos con información repetida.

Ahí tu propuesta de eliminar la página es una solución muy práctica considerando que lleva bastante tiempo sin actualizar y aún actualizada veo difícil darle mantenimiento si no es algo automático como mi propuesta.
